name: Production - Deploy to Azure Storage

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-22.04
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install
        npm run build-azure
    - name: Update Blobs
      uses: azure/cli@v2.1.0
      with:
        inlineScript: |
          tdnf install -y azcopy
          az storage blob sync -c '$web' -s dist --connection-string '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}'
