name: Deploy to Azure Storage - Stage

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install
        npm run build-azure-stage
    - name: Update Blobs
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az storage blob sync -c '$web' -s dist --connection-string '${{ secrets.AZURE_STORAGE_CONNECTION_STRING_STAGE }}'
